### ISSUE TITLE
Fails with co-dependency com.datomic/client-cloud v0.8.66: "No such var: client/Db"

### ISSUE THREAD

**Issue by kyptin** [ComputeSoftware/datomic-client-memdb#2]
I love the idea of this project, but it doesn't seem to work with the as-of-now latest version of the `com.datomic/client-cloud` library, v0.8.66. It does, however, work with the next-latest version, v0.8.63. Here's a reproducible test case.

`deps.edn`:

```clojure
{:deps
 {compute/datomic-client-memdb
  {:git/url "https://github.com/ComputeSoftware/datomic-client-memdb.git"
   :sha     "c17b57597c9f442adef931b653175b4341330bad"}
  ;; com.datomic/client-cloud {:mvn/version "0.8.66"}
  }}
```

`test.clj`:

```clojure
(require '[datomic.client.api :as d])
(require '[compute.datomic-client-memdb.core :as memdb])

(def client (memdb/client {}))
(def db-name "test")
(d/create-database client {:db-name db-name})
(def conn (d/connect client {:db-name db-name}))

(def schema
  [{:db/ident :clojure/version
    :db/valueType :db.type/string
    :db/unique :db.unique/value
    :db/cardinality :db.cardinality/one}])
(d/transact conn {:tx-data schema})

(d/transact conn {:tx-data [{:clojure/version (clojure-version)}]})
(def query '[:find ?v, :where [_ :clojure/version ?v]])
(def db (d/db conn))
(prn (d/q query db))
```

When I run the above code with the command `clojure -Srepro -Sforce test.clj`, I get:

```
#{["1.9.0"]}
```

However, if I uncomment the line in `deps.edn` (so that it depends on `com.datomic/client-cloud {:mvn/version "0.8.66"}`, I get an error, which I've appended below. If I change the version to `"0.8.63"`, it again prints `#{["1.9.0"]}`.

Here's the error I get:

```
Exception in thread "main" java.lang.RuntimeException: No such var: client/Db, compiling:(compute/datomic_client_memdb/core.clj:21:1)
	at clojure.lang.Compiler.analyzeSeq(Compiler.java:7010)
	at clojure.lang.Compiler.analyze(Compiler.java:6773)
	at clojure.lang.Compiler.analyze(Compiler.java:6729)
	at clojure.lang.Compiler$BodyExpr$Parser.parse(Compiler.java:6100)
	at clojure.lang.Compiler$LetExpr$Parser.parse(Compiler.java:6420)
	at clojure.lang.Compiler.analyzeSeq(Compiler.java:7003)
	at clojure.lang.Compiler.analyze(Compiler.java:6773)
	at clojure.lang.Compiler.analyze(Compiler.java:6729)
	at clojure.lang.Compiler$BodyExpr$Parser.parse(Compiler.java:6100)
	at clojure.lang.Compiler$FnMethod.parse(Compiler.java:5460)
	at clojure.lang.Compiler$FnExpr.parse(Compiler.java:4022)
	at clojure.lang.Compiler.analyzeSeq(Compiler.java:7001)
	at clojure.lang.Compiler.analyze(Compiler.java:6773)
	at clojure.lang.Compiler.eval(Compiler.java:7059)
	at clojure.lang.Compiler.load(Compiler.java:7514)
	at clojure.lang.RT.loadResourceScript(RT.java:379)
	at clojure.lang.RT.loadResourceScript(RT.java:370)
	at clojure.lang.RT.load(RT.java:460)
	at clojure.lang.RT.load(RT.java:426)
	at clojure.core$load$fn__6548.invoke(core.clj:6046)
	at clojure.core$load.invokeStatic(core.clj:6045)
	at clojure.core$load.doInvoke(core.clj:6029)
	at clojure.lang.RestFn.invoke(RestFn.java:408)
	at clojure.core$load_one.invokeStatic(core.clj:5848)
	at clojure.core$load_one.invoke(core.clj:5843)
	at clojure.core$load_lib$fn__6493.invoke(core.clj:5888)
	at clojure.core$load_lib.invokeStatic(core.clj:5887)
	at clojure.core$load_lib.doInvoke(core.clj:5868)
	at clojure.lang.RestFn.applyTo(RestFn.java:142)
	at clojure.core$apply.invokeStatic(core.clj:659)
	at clojure.core$load_libs.invokeStatic(core.clj:5925)
	at clojure.core$load_libs.doInvoke(core.clj:5909)
	at clojure.lang.RestFn.applyTo(RestFn.java:137)
	at clojure.core$apply.invokeStatic(core.clj:659)
	at clojure.core$require.invokeStatic(core.clj:5947)
	at clojure.core$require.doInvoke(core.clj:5947)
	at clojure.lang.RestFn.invoke(RestFn.java:408)
	at user$eval544.invokeStatic(test.clj:2)
	at user$eval544.invoke(test.clj:2)
	at clojure.lang.Compiler.eval(Compiler.java:7062)
	at clojure.lang.Compiler.load(Compiler.java:7514)
	at clojure.lang.Compiler.loadFile(Compiler.java:7452)
	at clojure.main$load_script.invokeStatic(main.clj:278)
	at clojure.main$script_opt.invokeStatic(main.clj:338)
	at clojure.main$script_opt.invoke(main.clj:333)
	at clojure.main$main.invokeStatic(main.clj:424)
	at clojure.main$main.doInvoke(main.clj:387)
	at clojure.lang.RestFn.applyTo(RestFn.java:137)
	at clojure.lang.Var.applyTo(Var.java:702)
	at clojure.main.main(main.java:37)
Caused by: java.lang.RuntimeException: No such var: client/Db
	at clojure.lang.Util.runtimeException(Util.java:221)
	at clojure.lang.Compiler.resolveIn(Compiler.java:7273)
	at clojure.lang.Compiler.resolve(Compiler.java:7243)
	at clojure.lang.Compiler$NewInstanceExpr.build(Compiler.java:7893)
	at clojure.lang.Compiler$NewInstanceExpr$DeftypeParser.parse(Compiler.java:7813)
	at clojure.lang.Compiler.analyzeSeq(Compiler.java:7003)
	... 49 more
```

**Comment by kyptin** [comment]
Well…perhaps not! I just grabbed the latest thing from Maven without checking whether it was officially supported. I just asked on the #datomic group on the Clojurians Slack; I'll report back if I hear anything useful.

**Comment by kennyjwilli** [comment]
Just saw the releases page update with 0.8.66 so I updated the lib for the new API changes in f011f3096900c993de3c0ba4d48d37217fce8247.
